

name: ETL PIPELINE WORKFLOW

on: 
    push: 
        branches: 
            - main


jobs: 
    extract-data-job: 
        runs-on: ubuntu-latest

        steps: 
            - name: checkout code
              uses: actions/checkout@v2

            - name: run extract.py
              run: python extract.py

    transform-data-job: 
        needs: extract-data-job
        runs-on: ubuntu-latest

        steps: 
            - name: checkout code
              uses: actions/checkout@v2

            - name: run transform.py
              run: python transform.py

    load-data-job: 
        needs: transform-data-job
        runs-on: ubuntu-latest

        steps: 
            - name: checkout code
              uses: actions/checkout@v2

            - name: run load.py
              run: python load.py